DROP TABLE IF EXISTS `storehouses_products`;

CREATE TABLE `storehouses_products` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT='складские запасы';

INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('1', 'et', 83722);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('2', 'molestias', 3617);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('3', 'porro', 309052);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('4', 'officia', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('5', 'omnis', 19109145);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('6', 'voluptates', 10143);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('7', 'doloribus', 1546659);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('8', 'quisquam', 78110603);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('9', 'exercitationem', 5905);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('10', 'iste', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('11', 'odio', 7517);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('12', 'officia', 34648);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('13', 'sequi', 23469);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('14', 'quia', 6443);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('15', 'rerum', 1859322);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('16', 'consequatur', 33910170);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('17', 'et', 945);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('18', 'optio', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('19', 'velit', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('20', 'adipisci', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('21', 'voluptatem', 7192);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('22', 'asperiores', 9991);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('23', 'quisquam', 4997610);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('24', 'dolor', 5659);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('25', 'dignissimos', 720);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('26', 'nihil', 48094331);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('27', 'doloremque', 8787);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('28', 'eligendi', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('29', 'autem', 8483);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('30', 'id', 46178126);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('31', 'rerum', 8117);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('32', 'ratione', 16522996);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('33', 'quidem', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('34', 'doloremque', 9970);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('35', 'quidem', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('36', 'hic', 4114);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('37', 'nostrum', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('38', 'velit', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('39', 'consectetur', 2970);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('40', 'et', 3166007);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('41', 'inventore', 93865495);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('42', 'rerum', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('43', 'qui', 9789);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('44', 'ea', 641);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('45', 'pariatur', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('46', 'voluptate', 8119);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('47', 'ex', 715508);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('48', 'et', 3750447);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('49', 'explicabo', 404509);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('50', 'repudiandae', 4760);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('51', 'perspiciatis', 66790484);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('52', 'pariatur', 1968);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('53', 'et', 20021);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('54', 'laudantium', 239814346);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('55', 'eius', 7115);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('56', 'dolor', 814650);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('57', 'totam', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('58', 'doloremque', 3512846);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('59', 'laudantium', 18357);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('60', 'eligendi', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('61', 'omnis', 42318);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('62', 'fugit', 18461);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('63', 'asperiores', 8549);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('64', 'qui', 600634941);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('65', 'cupiditate', 16402809);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('66', 'praesentium', 3892742);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('67', 'ea', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('68', 'debitis', 40772636);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('69', 'dolores', 2421);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('70', 'cum', 7834);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('71', 'possimus', 3779);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('72', 'esse', 7933);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('73', 'exercitationem', 480);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('74', 'temporibus', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('75', 'voluptatem', 170846744);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('76', 'cum', 2605);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('77', 'eum', 41063);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('78', 'quasi', 8092);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('79', 'fugit', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('80', 'eum', 777);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('81', 'architecto', 10056);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('82', 'numquam', 6275);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('83', 'quod', 8788);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('84', 'est', 28936);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('85', 'vitae', 7586);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('86', 'praesentium', 5449);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('87', 'occaecati', 8234);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('88', 'odit', 6564);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('89', 'amet', 343464398);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('90', 'a', 68732);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('91', 'nisi', 13961207);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('92', 'omnis', 328100163);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('93', 'vel', 396224832);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('94', 'aut', 9863);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('95', 'temporibus', 0);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('96', 'sunt', 4645107);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('97', 'distinctio', 5543);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('98', 'aperiam', 5092);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('99', 'saepe', 1384);
INSERT INTO `storehouses_products` (`id`, `name`, `value`) VALUES ('100', 'in', 9159);


SELECT * FROM storehouses_products ORDER BY value = 0, value;